### ISSUE TITLE
ElasticSearch 1.x support

### ISSUE THREAD

**Issue by roflmao** [mattweber/es2graphite#1]
Doesnt seem to be any backwards compatibility in 1.x api for stats:

```
'2014-03-24 09:03:01: GET http://rd03:9200/_cluster/nodes/stats?all=true'
Unhandled exception in thread started by <function get_metrics at 0x1b7fb90>
Traceback (most recent call last):
  File "./es2graphite.py", line 129, in get_metrics
    node_stats_data = urllib2.urlopen(node_stats_url).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by Ralnoc** [comment]
This was resolved with #4 and can be closed.
