### ISSUE TITLE
Index Level process section failes

### ISSUE THREAD

**Issue by Ralnoc** [mattweber/es2graphite#14]
When including index level data processing you get the traceback of:

```
Traceback (most recent call last):
  File "./es2graphite.py", line 290, in <module>
    get_metrics()
  File "./es2graphite.py", line 240, in get_metrics
    indices_stats_metrics = process_indices_stats(args.prefix, indices_stats)
  File "./es2graphite.py", line 121, in process_indices_stats
    process_section(int(time.time()), metrics, (prefix, CLUSTER_NAME, 'indices'), stats['indices'])
TypeError: process_section() takes exactly 5 arguments (4 given)
```

**Comment by mattweber** [comment]
Fixed via #13
